---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-config
  namespace: unbound
data:
  unbound.conf: |-
    server:
        interface: 0.0.0.0
        access-control: 192.168.0.0/16 allow
        access-control: 172.16.0.0/12 allow
        access-control: 10.0.0.0/8 allow
        verbosity: 1
        logfile: ""

    forward-zone:
        name: "."
        forward-addr: 1.1.1.1
        forward-addr: 1.0.0.1
