---
apiVersion: v1
kind: Service
metadata:
  name: unbound
  namespace: unbound
spec:
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  selector:
    app: unbound
  type: LoadBalancer
